main.py
from app_connector import create_myApp

#creating a flask app
app = create_myApp()

if(__name__ == "__main__"):
    app.run(port = 5000)

routes.py
# importing flask framework
from flask import Flask, flash, render_template, request, redirect, url_for
# importing the os module
import os
from os.path import pathsep
from flask import Blueprint,send_from_directory, send_file
from csv_logic.csvLogic import CsvLogic
from database.db_schema import Payload, Admin


route =  Blueprint("route",__name__) 
HOTEL_PIC = ['../static/img/team/hotel8.jpg','../static/img/team/hotel2.jpg',
    '../static/img/team/hotel3.jpg', '../static/img/team/hotel9.jpg', '../static/img/team/hotel4.jpg', 
    '../static/img/team/hotel1.jpg', '../static/img/team/hotel6.jpg'
    ]

@route.route("/",methods=["GET","POST"])
def home():
    db_data = Payload.query.limit(6).all()
    all_hotels = Payload.query.all()
  
    if request.method == "POST":
        name = request.form.get("name").title()
        print(name)
        hotel_detail = Payload.query.filter_by(hotel_name=name).all()
        if len(hotel_detail) > 0:
            return render_template("html/preview_multiple.html",details = hotel_detail)
        #    return redirect(url_for("route.preview", details =hotel_detail))
        else:
            flash(f"There is no record for {name} ",category="error")
    # setting the html template 'template/index.html
    return render_template("index.html", hotels = db_data , all_hotels = all_hotels, hotel_pic = HOTEL_PIC)

@route.route("/admin/<user_id>",methods =["GET,POST"])
def admin(user_id):

            # setting the html template 'template/admin.html
            return render_template("html/admin.html", user_id = user_id, download='<download>')
       


@route.route("/preview/<name>")
def preview(name):
    hotel_detail = Payload.query.filter_by(hotel_name=name).all()
    # setting the html template 'template/setup.html
    return render_template("html/preview.html",details = hotel_detail)

@route.route("/hotels")
def hotels():
    all_hotels = Payload.query.all()
    # setting the html template 'template/all_hotels.html
    return render_template("html/all_hotels.html",hotels = reversed(all_hotels),hotel_pic = HOTEL_PIC)


@route.route("/download/<download>",methods=['GET', 'POST'])
def download(download):
    from app_connector import create_myApp
    app= create_myApp()
    uploads = os.path.join(app.root_path,app.config['UPLOAD_FOLDER'],)
    # setting the html template 'template/loading_animation.html
    return send_from_directory(directory=uploads, path=download, as_attachment=True)

templates/html/admin.html
{%  extends 'html/layout.html' %}

{% block body %}
<header class="bg-gradient-dark">
    <div class="page-header min-vh-75" style="background-image: url('https://th.bing.com/th/id/R.9f2f6ab1dd43d3ec74261bb0e31d8205?rik=pweQ5cA6tkfwnw&pid=ImgRaw&r=0');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Upload Your CSV File here</h1>
           
            
            <form action=""method="POST" enctype="multipart/form-data">
                <p><input type="file"  class="btn bg-gradient-dark" name="file"></p>
                <p><button type="submit" class="btn btn-primary">Submit</button></p>
                <!-- <div class="spinner-border text-primary"></div> -->
            </form>
            
            {% if path|length > 1 %}
              <div class="row">
                <div class="col-md-6 col-lg-6">
                  <p style="color: white;">{{path}}</p>
                </div>
                <div class="col-md-6 col-lg-6">
                  <button type="submit" class="btn btn-secondary">
                    <a href="{{ url_for('route.download' ,download = path) }}"  style=" color: white; text-decoration: none;">
                      Download
                    </a>
                  </button>
                </div> 
                </div>
              {% else %} 
             <div> </div>
              {% endif %}
            
          </div>
        </div>
      </div>
    </div>
  </header>

</div>

 
<div>
  <p id="our-service"><span id="our">Upload</span> File Guideline</p>
  <p id="service-caption">Ensure you follow the steps highlighted below before<br> uploading a csv file</p>
</div>
<div class="container">
    <Ol>
        <li> Ensure your dataset has a column for hotel names titled <strong>name</strong> </li>
        <li> Ensure your dataset has a column for countries titled <strong>country</strong></li>
        <li> Ensure your dataset has a column for cities titled <strong>city</strong></li>
        <li> Ensure your dataset has a column for address titled <strong>address</strong></li>
        <li> Ensure your dataset has a column for hotel reviews titled <strong>review</strong></li>
        <li> Ensure your dataset has a column for hotel ratings titled <strong>rating</strong></li>
        <li> Ensure your dataset has a column for  rating classified into your expected impressions titled <strong>expectation</strong></li>
    </Ol>


    
</div>
     <!-- ======= Footer ======= -->
     <footer id="footer">
      <div class="container">
        <h3>True Review</h3>
        <p>Classifing Reviews the proper way</p>
        <div class="credits">
          <a href="{{url_for('auth.Logout')}}">Logout</a>
        </div>
        <div class="copyright">
          &copy; Copyright <strong><span>Tomisin Oladele (Teeto)</span></strong>. All Rights Reserved
        </div>
       
      </div>
    </footer><!-- End Footer -->

{% endblock %} 

templates/html/all_hotels.html
{%  extends 'html/layout.html' %}

{% block body %}
       <!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center  header-dark ">
    <div class="container d-flex align-items-center justify-content-between">
  
      <div class="logo">
        <h1><a href="/">Tomisin</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>
  
      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
  
    </div>
  </header>
  <!-- End Header -->
  <main id="main">
    <!-- ======= Services Section ======= -->
<section id="services" class="services">
    <div class="container">
      <div class="section-title" data-aos="zoom-out">
        <h2>Hotels</h2>
        <p>Browse Hotels</p>
      </div>
    
      <div class="row">
        {% for key in hotels %}
        <div class="col-lg-4 col-md-6" id="space">
          <a href="{{url_for('route.preview', name=key.hotel_name)}}" style="text-decoration: none;">
          <div class="icon-box" >
            <!-- <div class="icon"><i class="bi bi-briefcase" style="color: #ff689b;"></i></div> -->
            {%if key.bert_impression  == 'positive'%}
            <img src="{{hotel_pic[0]}}" alt="alt">
            {% elif key.bert_impression == 'negative'%}
            <img src="{{hotel_pic[4]}}" alt="alt">
            {%else %}
            <img src="{{hotel_pic[3]}}" alt="alt">
            {%endif%}
            <h4 class="title">{{key.hotel_name}}</h4>
            <p class="description">Address: {{key.hotel_address}}</p>
            <p class="description" style="color: black;">CITY: {{key.hotel_city}}</p>
            <p class="description" > Classification:  
              {%if key.bert_impression == 'positive'%}
              <span style="color: green; font-weight: 700;"> {{key.bert_impression.title()}}</span>
              {% elif key.bert_impression == 'negative' %}
              <span style="color: red; font-weight: 700;"> {{key.bert_impression.title()}}</span>
              {% else %}
              <span style="color: orange; font-weight: 700;"> {{key.bert_impression.title()}}</span>
              {% endif %}
              Review
            </p>
          
          </div>
        </a>
        </div>
        {% endfor%}
       
      </div>
    
    </div>
    </section>
    <!-- End Services Section -->
    
    </main><!-- End #main -->
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>True Review</h3>
      <p>Classifing Reviews the proper way</p>
   
      <div class="copyright">
        &copy; Copyright <strong><span>Tomisin Oladele (Teeto)</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
      </div>
    </div>
  </footer><!-- End Footer -->

{% endblock %} 

templates/html/error.html
{%  extends 'html/layout.html' %}

{% block body %}
<div class="container" id="error">
    <h1 class="first-four">4</h1>
    <div class="cog-wheel1">
        <div class="cog1">
          <div class="top"></div>
          <div class="down"></div>
          <div class="left-top"></div>
          <div class="left-down"></div>
          <div class="right-top"></div>
          <div class="right-down"></div>
          <div class="left"></div>
          <div class="right"></div>
      </div>
    </div>
    
    
   <h1 class="second-four">1</h1>
    <p class="wrong-para">You are unauthorize</p>
  </div>

{% endblock %} 

templates/html/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
        <link rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />
        <link rel="stylesheet" href="{{ url_for('static', filename ='css/style.css')}}"/>
        <link rel="stylesheet" href="{{ url_for('static', filename ='css/style2.css')}}"/>
          <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
   <!-- Google Fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Nucleo Icons -->
  <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ url_for('static', filename ='css/material-kit.css')}}" rel="stylesheet" />
        
  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename ='vendor/animate.css/animate.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/aos/aos.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename ='vendor/swiper/swiper-bundle.min.css')}}" rel="stylesheet">

        
        <title>{% block title%}Tomisin Sentiment Analysis{% endblock %}</title>
    </head>
    <body>
        <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbar"
            >
            <span class="navbar-toggler-icon"></span> -->
              <!--<span class="navbar-toggler-icon"></span>-->
            <!-- </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                 
                  <a class="nav-item nav-link" id="Home" href="/">Home</a>
                  <a class="nav-item nav-link" id="Logout" href="/logout">Logout</a>
                  <a class="nav-item nav-link" id="Login" href="/login">Login</a>
                  <a class="nav-item nav-link" id="Sign up" href="/setup">Sign up</a>
                  
                </div>
              </div>
          </nav> -->
          
    
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          {% if category == "error" %} 
          <div class="alert alert-danger alter-dismissable fade show" role="alert" style="color: white;">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert" style="color: white;">
           {{ message }}
           <button type="button" class="close" data-dismiss="alert">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
          {% endif%}
          {% endfor %}
          {% endif %}
          {% endwith %}
  
          
         {% block body %}
         
        {% endblock %}

      

      <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename ='vendor/aos/aos.js')}}"></script>
  <script src="{{ url_for('static', filename ='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{ url_for('static', filename ='vendor/glightbox/js/glightbox.min.js')}}"></script>
  <script src="{{ url_for('static', filename ='vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
  <script src="{{ url_for('static', filename ='vendor/swiper/swiper-bundle.min.js')}}"></script>
  

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename ='js/main.js')}}"></script>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!--   Core JS Files   -->
  <script src="{{ url_for('static', filename ='js/core/popper.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename ='js/core/bootstrap.min.js')}}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename ='js/plugins/perfect-scrollbar.min.js')}}"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ url_for('static', filename ='js/plugins/parallax.min.js')}}"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ url_for('static', filename ='js/material-kit.min.js')}}" type="text/javascript"></script>

</html>

templates/html/login.html
{%  extends 'html/layout.html' %}
{% block title%} Login page{% endblock%}
{% block body %}

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
  <div class="container d-flex align-items-center justify-content-between">

    <div class="logo">
      <h1><a href="/">True Review</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
    </div>
  </div>
</header><!-- End Header -->


<div class="page-header align-items-start min-vh-100" class="background", id="login-background" >
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
          <div class="card z-index-0 fadeIn3 fadeInBottom">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Welcome Back</h4>
                <div class="row mt-3">
        
                </div>
              </div>
            </div>
            <div class="card-body">
              <form action=""method="POST" enctype="multipart/form-data" role="form" class="text-start">
                <div class="input-group input-group-outline my-3">
                  <label class="form-label"></label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email" >
                </div>
                <div class="input-group input-group-outline mb-3">
                  <label class="form-label"></label>
                  <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
                </div>
                <!-- <div class="form-check form-switch d-flex align-items-center mb-3">
                  <input class="form-check-input" type="checkbox" id="rememberMe" checked>
                  <label class="form-check-label mb-0 ms-3" for="rememberMe">Remember me</label>
                </div> -->
                <div class="text-center">
                  <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Login</button>
                </div>
                <p class="mt-4 text-sm text-center">
                 <a href="/register" >Don't have an account? Sign up</a>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}  

templates/index.html
{%  extends 'html/layout.html' %}

{% block body %}

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center  header-transparent ">
  <div class="container d-flex align-items-center justify-content-between">

    <div class="logo">
      <h1><a href="/">True Review</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
    </div>

    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
        <!-- <li><a class="nav-link scrollto" href="/login">Admin</a></li> -->
        <li><a class="nav-link scrollto" href="#services">Hotels</a></li>
        <li><a class="nav-link scrollto " href="#about">About</a></li>
        
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

  </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-end align-items-center">
  <div id="heroCarousel" data-bs-interval="5000" class="container carousel carousel-fade" data-bs-ride="carousel">

    <!-- Slide 1 -->
    <div class="carousel-item active">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Find The Best <span>Hotel With Ease </span></h2>
        <p class="animate__animated fanimate__adeInUp">Lets help you find the appropriatte hotels for your next staycation using our optimize review system 
      </p>
        <!-- <form action="" method="POST" enctype="multipart/form-data">
          <div class="col-md-12 col-lg-12 form-group">
            <input type="text" name="name" class="form-control" id="name" placeholder="Hotel" required>
          </div>
          <div class="btn-get-started animate__animated animate__fadeInUp scrollto text-center "><button type="submit">Search</button></div>
        </form> -->
      </div>
    </div>

    <!-- Slide 2 -->
    <div class="carousel-item">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Know Where It Truly Belong</h2>
        <p class="animate__animated animate__fadeInUp">You don't have to stay in a messy hotel because of some crappy start ratings. Find out where that hotel truly belong 
          and see the best hotels around you</p>
          <!-- <form action="" method="POST" enctype="multipart/form-data">
            <div class="col-md-12 col-lg-12 form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Hotel" required>
            </div>
            <div class="btn-get-started animate__animated animate__fadeInUp scrollto text-center "><button type="submit">Search</button></div>
          </form> -->
        </div>
    </div>

   

    <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
    </a>

    <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
    </a>

  </div>

  <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
    <defs>
      <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
    </defs>
    <g class="wave1">
      <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
    </g>
    <g class="wave2">
      <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
    </g>
    <g class="wave3">
      <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
    </g>
  </svg>

</section><!-- End Hero -->

<main id="main">

<!-- ======= Services Section ======= -->
<section id="services" class="services">
<div class="container">

  <div class="section-title" data-aos="zoom-out">
    <h2>Hotels</h2>
    <p>Browse Hotels</p>
  </div>

  <div class="row">
    {% for key in hotels %}
    <div class="col-lg-4 col-md-6" id="space">
      <a href="{{url_for('route.preview', name=key.hotel_name)}}">
      <div class="icon-box" >
        <img src= "{{hotel_pic[key.id]}}" alt="alt">
        <h4 class="title">{{key.hotel_name}}</h4>
        <p class="description">Address: {{key.hotel_address}}</p>
        <p class="description" style="color: black;">CITY: {{key.hotel_city}}</p>
        <p class="description" > Classification:  
          {%if key.bert_impression == 'positive'%}
          <span style="color: green; font-weight: 700;"> {{key.bert_impression.title()}}</span>
          {% elif key.bert_impression == 'negative' %}
          <span style="color: red; font-weight: 700;"> {{key.bert_impression.title()}}</span>
          {% else %}
          <span style="color: orange; font-weight: 700;"> {{key.bert_impression.title()}}</span>
          {% endif %}
          Review
        </p>
       
        <!-- <div class="row ">
          <div class="col-md-6  text-center" id="code" style="color: #000;">
            <p>Classification:</p>
          </div>
          <div class="col-lg-4 col-md-6 ">
            {%if key.bert_impression == 'positive'%}
            <p class="title" style="color: green;"> <span> {{key.bert_impression.title()}}</span> </p>
            {% elif key.bert_impression == 'negative' %}
            <p class="title" style="color: red;"> <span> {{key.bert_impression.title()}}</span> </p>
            {% else %}
            <p class="title" style="color: orange;"> <span> {{key.bert_impression.title()}}</span>  </p>
            {% endif %}
          </div>
        
        </div> -->
      </a> 
      </div>
    </div>
    {% endfor%}
    <h4 class="title"><a href="{{url_for('route.hotels')}}">See More</a></h4>
     </div>
  
</div>
</section>
<!-- End Services Section -->

  <!-- ======= About Section ======= -->
  <section id="about" class="about">
    <div class="container">

      <div class="section-title" data-aos="zoom-out">
        <h2>About</h2>
        <p>About us</p>
      </div>

      <div class="row content" data-aos="fade-up">
        <div class="col-lg-6">
          <p>
            How Our System Works:
          </p>
          <ul>
            <li><i class="ri-check-double-line"></i> All hotel reviews on our websites have been automatically classified using our algorithm to spare you the stress of making bad hotel choices.</li>
          </ul>
        </div>
        <div class="col-lg-6 pt-4 pt-lg-0">
        </div>
      </div>
    </div>
  </section>
  <!-- End About Section -->
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer">
  <div class="container">
    <h3>True Review</h3>
    <p>Classifing Reviews the proper way</p>
 
    <div class="copyright">
      &copy; Copyright <strong><span>Tomisin Oladele (Teeto)</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
    </div>
  </div>
</footer><!-- End Footer -->

<!-- <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a> -->

<!-- Vendor JS Files -->
<script src="../static/vendor/aos/aos.js"></script>
<script src="../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../static/vendor/glightbox/js/glightbox.min.js"></script>
<script src="../static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="../static/vendor/swiper/swiper-bundle.min.js"></script>
<script src="../static/vendor/php-email-form/validate.js"></script>
{% endblock %}  